### ISSUE TITLE
Tile wisdoms so more fit on a page

### ISSUE THREAD

**Issue by LowBudgetMan** [sapphon/upwise#4]
On a larger screen it's hard to look at wisdoms in a list view. Is there a way that they can be tiled to better fit on the screen?

**Comment by sapphon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Users can view wisdoms in a tiled format](https://trello.com/c/4AbkN9ut/121-users-can-view-wisdoms-in-a-tiled-format)

**Comment by sapphon** [comment]
This feature has been shipped, although the UI currently does not highlight it.  Replace the "board" in "leaderboard" with the word "matrix" to try it out: https://upwise.cfapps.io/wisdomleadermatrix
